In [1]:
import pandas as pd
import Sastrawi
import math # untuk perhitungan bobot sentence
import string

In [2]:
f = open('naskah.txt', 'r')
dokumen = f.read()
print(dokumen)

"Maria Sharapova has basically no friends as tennis players on the WTA Tour. The Russian player has no problems in openly speaking about it and in a recent interview she said: â€˜I donâ€™t really hide any feelings too much.I think everyone knows this is my job here. When Iâ€™m on the courts or when Iâ€™m on the court playing, Iâ€™m a competitor and I want to beat every single person whether theyâ€™re in the locker room or across the net.So Iâ€™m not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match.Iâ€™m a pretty competitive girl. I say my hellos, but Iâ€™m not sending any players flowers as well. Uhm, Iâ€™m not really friendly or close to many players.
I have not a lot of friends away from the courts.â€™ When she said she is not really close to a lot of players, is that something strategic that she is doing? Is it different on the menâ€™s tour than the womenâ€™s tour? â€˜No, not at all.
I think just because youâ€™re in the same sport doesnâ€™t mean that you have to be friends with everyone just because youâ€™re categorized, youâ€™re a tennis player, so youâ€™re going to get along with tennis players.
I think every person has different interests. I have friends that have completely different jobs and interests, and Iâ€™ve met them in very different parts of my life.
I think everyone just thinks because weâ€™re tennis players we should be the greatest of friends. But ultimately tennis is just a very small part of what we do.
There are so many other things that weâ€™re interested in, that we do."

In [3]:
bersih = dokumen.lower()
print(bersih)

"maria sharapova has basically no friends as tennis players on the wta tour. the russian player has no problems in openly speaking about it and in a recent interview she said: â€˜i donâ€™t really hide any feelings too much.i think everyone knows this is my job here. when iâ€™m on the courts or when iâ€™m on the court playing, iâ€™m a competitor and i want to beat every single person whether theyâ€™re in the locker room or across the net.so iâ€™m not the one to strike up a conversation about the weather and know that in the next few minutes i have to go and try to win a tennis match.iâ€™m a pretty competitive girl. i say my hellos, but iâ€™m not sending any players flowers as well. uhm, iâ€™m not really friendly or close to many players.
i have not a lot of friends away from the courts.â€™ when she said she is not really close to a lot of players, is that something strategic that she is doing? is it different on the menâ€™s tour than the womenâ€™s tour? â€˜no, not at all.
i think just because youâ€™re in the same sport doesnâ€™t mean that you have to be friends with everyone just because youâ€™re categorized, youâ€™re a tennis player, so youâ€™re going to get along with tennis players.
i think every person has different interests. i have friends that have completely different jobs and interests, and iâ€™ve met them in very different parts of my life.
i think everyone just thinks because weâ€™re tennis players we should be the greatest of friends. but ultimately tennis is just a very small part of what we do.
there are so many other things that weâ€™re interested in, that we do."

In [10]:
import nltk
from nltk.tokenize import word_tokenize
kalimats = nltk.sent_tokenize(bersih)

In [11]:
kalimats

['"maria sharapova has basically no friends as tennis players on the wta tour.',
 'the russian player has no problems in openly speaking about it and in a recent interview she said: â€˜i donâ€™t really hide any feelings too much.i think everyone knows this is my job here.',
 'when iâ€™m on the courts or when iâ€™m on the court playing, iâ€™m a competitor and i want to beat every single person whether theyâ€™re in the locker room or across the net.so iâ€™m not the one to strike up a conversation about the weather and know that in the next few minutes i have to go and try to win a tennis match.iâ€™m a pretty competitive girl.',
 'i say my hellos, but iâ€™m not sending any players flowers as well.',
 'uhm, iâ€™m not really friendly or close to many players.',
 'i have not a lot of friends away from the courts.â€™ when she said she is not really close to a lot of players, is that something strategic that she is doing?',
 'is it different on the menâ€™s tour than the womenâ€™s tour?',
 'â€˜no, not at all.',
 'i think just because youâ€™re in the same sport doesnâ€™t mean that you have to be friends with everyone just because youâ€™re categorized, youâ€™re a tennis player, so youâ€™re going to get along with tennis players.',
 'i think every person has different interests.',
 'i have friends that have completely different jobs and interests, and iâ€™ve met them in very different parts of my life.',
 'i think everyone just thinks because weâ€™re tennis players we should be the greatest of friends.',
 'but ultimately tennis is just a very small part of what we do.',
 'there are so many other things that weâ€™re interested in, that we do."']

In [12]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
vektor = TfidfVectorizer()

In [14]:
matrik_tfidf = vektor.fit_transform(kalimats)
print(matrik_tfidf)

  (0, 121)	0.2931205517930431
  (0, 139)	0.3386668189240463
  (0, 111)	0.18294310304532696
  (0, 75)	0.2608049609846867
  (0, 84)	0.19794280673679465
  (0, 108)	0.2152586938536834
  (0, 7)	0.2931205517930431
  (0, 34)	0.2152586938536834
  (0, 72)	0.2608049609846867
  (0, 10)	0.3386668189240463
  (0, 41)	0.2608049609846867
  (0, 97)	0.3386668189240463
  (0, 62)	0.3386668189240463
  (1, 44)	0.1963815364957438
  (1, 53)	0.1963815364957438
  (1, 69)	0.1512320549341207
  (1, 50)	0.13669716834983528
  (1, 118)	0.1963815364957438
  (1, 57)	0.1963815364957438
  (1, 29)	0.1512320549341207
  (1, 116)	0.13669716834983528
  (1, 68)	0.1963815364957438
  (1, 120)	0.1963815364957438
  (1, 30)	0.1963815364957438
  (1, 5)	0.16997078285519301
  :	:
  (12, 24)	0.2916571320670097
  (12, 133)	0.3369760070709206
  (12, 80)	0.3369760070709206
  (12, 101)	0.3369760070709206
  (12, 124)	0.3369760070709206
  (12, 129)	0.2595028785403897
  (12, 127)	0.2916571320670097
  (12, 55)	0.2595028785403897
  (12, 74)	0.23456210186759213
  (12, 14)	0.2916571320670097
  (12, 50)	0.23456210186759213
  (12, 108)	0.21418400353647876
  (13, 47)	0.30236567127054653
  (13, 115)	0.30236567127054653
  (13, 79)	0.30236567127054653
  (13, 6)	0.30236567127054653
  (13, 113)	0.30236567127054653
  (13, 24)	0.261701434724769
  (13, 129)	0.23284969974135336
  (13, 132)	0.261701434724769
  (13, 61)	0.261701434724769
  (13, 110)	0.3843709263911516
  (13, 102)	0.23284969974135336
  (13, 88)	0.2104705554627161
  (13, 46)	0.1921854631955758

In [15]:
# menampilkan bobot TFIDF
Doc_Term_Matrix = pd.DataFrame(matrik_tfidf.toarray(), columns = vektor.get_feature_names())
pd.set_option('display.precision', 2) # format angka
hasil = Doc_Term_Matrix.to_excel('hasiltfidf.xlsx')

In [16]:
Doc_Term_Matrix

,about,across,all,along,and,any,are,as,at,away,...,weâ,what,when,whether,win,with,womenâ,wta,you,youâ
0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.29,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.34,0.00,0.00
1,0.17,0.00,0.00,0.00,0.15,0.17,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,0.09,0.11,0.00,0.00,0.25,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.19,0.11,0.11,0.00,0.00,0.00,0.00,0.00
3,0.00,0.00,0.00,0.00,0.00,0.29,0.0,0.29,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
5,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.18,...,0.00,0.00,0.16,0.00,0.00,0.00,0.00,0.00,0.00,0.00
6,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.32,0.00,0.00,0.00
7,0.00,0.00,0.58,0.00,0.00,0.00,0.0,0.00,0.58,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
8,0.00,0.00,0.00,0.14,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.28,0.00,0.00,0.14,0.56
9,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
10,0.00,0.00,0.00,0.00,0.36,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
11,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,...,0.27,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
12,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.34,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
13,0.00,0.00,0.00,0.00,0.00,0.00,0.3,0.00,0.00,0.00,...,0.26,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [17]:
def find_average_score(Doc_Term_Matrix):
    """
    Calculate average value of a sentence from the sentence score table.
    """
    print('Finding average score')
    hasil = []
    for kata in range(0, len(Doc_Term_Matrix)):
        sum = 0
        jumkata = 0
        for val in Doc_Term_Matrix:
            if Doc_Term_Matrix[val][kata]>0:
                sum += Doc_Term_Matrix[val][kata]
                jumkata = jumkata+1
        average = sum / jumkata
        hasil.append(average)
    return hasil

In [18]:
kalimatspd = pd.DataFrame(kalimats)
hasilskor = pd.DataFrame(find_average_score(Doc_Term_Matrix))

Finding average score

In [19]:
hasilskor

       0
0   0.27
1   0.18
2   0.13
3   0.28
4   0.31
5   0.20
6   0.32
7   0.49
8   0.16
9   0.41
10  0.23
11  0.25
12  0.29
13  0.27

In [21]:
kalimatspd

                                                    0
0   "maria sharapova has basically no friends as t...
1   the russian player has no problems in openly s...
2   when iâ€™m on the courts or when iâ€™m on the ...
3   i say my hellos, but iâ€™m not sending any pla...
4   uhm, iâ€™m not really friendly or close to man...
5   i have not a lot of friends away from the cour...
6   is it different on the menâ€™s tour than the w...
7                                  â€˜no, not at all.
8   i think just because youâ€™re in the same spor...
9       i think every person has different interests.
10  i have friends that have completely different ...
11  i think everyone just thinks because weâ€™re t...
12  but ultimately tennis is just a very small par...
13  there are so many other things that weâ€™re in...

In [22]:
# sebelum penggabungan kalimat dan skor setiap kalimat, karena kalimat masih dalam bentuk list
# maka kita ubah dulu menjadi dataframe

hasilakhir = pd.concat([kalimatspd,hasilskor], axis=1)
hasilakhir.columns = ['kalimat','skor']
print(hasilakhir)

                                              kalimat  skor
0   "maria sharapova has basically no friends as t...  0.27
1   the russian player has no problems in openly s...  0.18
2   when iâ€™m on the courts or when iâ€™m on the ...  0.13
3   i say my hellos, but iâ€™m not sending any pla...  0.28
4   uhm, iâ€™m not really friendly or close to man...  0.31
5   i have not a lot of friends away from the cour...  0.20
6   is it different on the menâ€™s tour than the w...  0.32
7                                  â€˜no, not at all.  0.49
8   i think just because youâ€™re in the same spor...  0.16
9       i think every person has different interests.  0.41
10  i have friends that have completely different ...  0.23
11  i think everyone just thinks because weâ€™re t...  0.25
12  but ultimately tennis is just a very small par...  0.29
13  there are so many other things that weâ€™re in...  0.27

In [28]:
print(' HASIL SUMMARY :')
Filter = hasilakhir.loc[hasilakhir['skor']>=0.4]
print(Filter['kalimat'])

 HASIL SUMMARY :
7                               â€˜no, not at all.
9    i think every person has different interests.
Name: kalimat, dtype: object